services:
  portfolio-dev:
    image: portfolio-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
